DROP TABLE MOVIE CASCADE CONSTRAINTS;
DROP TABLE MOVIE_GENRES CASCADE CONSTRAINTS;
DROP TABLE MOVIE_COUNTRIES CASCADE CONSTRAINTS;
DROP TABLE MOVIE_LOCATIONS CASCADE CONSTRAINTS;
DROP TABLE TAG CASCADE CONSTRAINTS;
DROP TABLE MOVIE_TAGS CASCADE CONSTRAINTS;
